### ISSUE TITLE
Go < 1.6 broken in v3

### ISSUE THREAD

**Issue by tamird** [actions/setup-go#216]
See CI failures in this dependabot PR: https://github.com/petermattis/goid/pull/20.

```
Run actions/setup-go@v3
  with:
    go-version: 1.5
    check-latest: false
    token: ***
Setup go version spec 1.5
Attempting to download 1.5...
matching 1.5...
Not found in manifest.  Falling back to download directly from Go
Install from dist
Acquiring go1.5.4 from https://storage.googleapis.com/golang/go1.5.4.linux-amd64.tar.gz
Extracting Go...
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/4b345075-4de7-438c-bea7-106[2](https://github.com/petermattis/goid/runs/5973402225?check_suite_focus=true#step:3:2)7b[3](https://github.com/petermattis/goid/runs/5973402225?check_suite_focus=true#step:3:3)ab7bb -f /home/runner/work/_temp/cf1[4](https://github.com/petermattis/goid/runs/5973402225?check_suite_focus=true#step:3:4)[5](https://github.com/petermattis/goid/runs/5973402225?check_suite_focus=true#step:3:5)041-31[6](https://github.com/petermattis/goid/runs/5973402225?check_suite_focus=true#step:3:6)3-45e[7](https://github.com/petermattis/goid/runs/5973402225?check_suite_focus=true#step:3:7)-94d[8](https://github.com/petermattis/goid/runs/5973402225?check_suite_focus=true#step:3:8)-30[9](https://github.com/petermattis/goid/runs/5973402225?check_suite_focus=true#step:3:9)2b193f936
Successfully extracted go to /home/runner/work/_temp/4b345075-4de7-438c-bea7-[10](https://github.com/petermattis/goid/runs/5973402225?check_suite_focus=true#step:3:10)627b3ab7bb
Adding to the cache ...
Successfully cached go to /opt/hostedtoolcache/go/1.5.4/x64
Added go to the path
Successfully setup go version 1.5
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

AssertionError [ERR_ASSERTION]: a path argument must be provided
    at Object.<anonymous> (/home/runner/work/_actions/actions/setup-go/v3/dist/index.js:5547:18)
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/actions/setup-go/v3/dist/index.js:5487:71
    at new Promise (<anonymous>)
    at module.exports.672.__awaiter (/home/runner/work/_actions/actions/setup-go/v3/dist/index.js:5483:[12](https://github.com/petermattis/goid/runs/5973402225?check_suite_focus=true#step:3:12))
    at Object.mkdirP (/home/runner/work/_actions/actions/setup-go/v3/dist/index.js:5546:12)
    at Object.<anonymous> (/home/runner/work/_actions/actions/setup-go/v3/dist/index.js:[20](https://github.com/petermattis/goid/runs/5973402225?check_suite_focus=true#step:3:20)4:[22](https://github.com/petermattis/goid/runs/5973402225?check_suite_focus=true#step:3:22))
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/actions/setup-go/v3/dist/index.js:57:71
    at new Promise (<anonymous>) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: '',
  expected: true,
  operator: '=='
}
```

**Comment by IvanZosimov** [comment]
Hello, @tamird 👋 
Thanks a lot for reporting this issue!
We will take a look at it and provide you with a response as soon as possible.

**Comment by vsafonkin** [comment]
Hi @tamird, pull request with fix for this bug was merged, these changes will be available after release of new action version or via `actions/setup-go@main` at the moment.

Closed, please contact us if you have any questions, thank you!

**Comment by tamird** [comment]
Thanks! Would you mind pinging this issue when the fix has been released?

**Comment by vsafonkin** [comment]
@tamird, sure!
