### ISSUE TITLE
(node:3075210) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: a path argument must be provided

### ISSUE THREAD

**Issue by ginwakeup** [actions/setup-go#286]
**Description:**
setup-go v2/v3 errors out (it wasn't before) with an assertionError as some path was not provided.

**Action version:**
v2 and v3.

**Platform:**
- [x] Ubuntu

**Runner type:**
- [x] Self-hosted

**Tools version:**
1.18.1

**Repro steps:**  
1. Create action
2. Use setup-go
3. Run go install cmd

**Expected behavior:**
Not to error out

**Actual behavior:**
Action errors out asking for a path in the setup-go step:

```
Setup go stable version spec 1.18.1
Attempting to resolve the latest version from the manifest...
matching 1.18.1...
Resolved as '1.18.1'
Found in cache @ /actions-runner/_work/_tool/go/1.18.1/x64
Added go to the path
Successfully setup go version 1.18.1
(node:3076949) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: a path argument must be provided
    at Object.<anonymous> (/actions-runner/_work/_actions/actions/setup-go/v2/dist/index.js:5550:18)
    at Generator.next (<anonymous>)
    at /actions-runner/_work/_actions/actions/setup-go/v2/dist/index.js:5490:71
    at new Promise (<anonymous>)
    at module.exports.672.__awaiter (/actions-runner/_work/_actions/actions/setup-go/v2/dist/index.js:5486:[12](https://github.rockstargames.com/tech-art/rsg_grpc_transcoding/runs/48704?check_suite_focus=true#step:5:12))
    at Object.mkdirP (/actions-runner/_work/_actions/actions/setup-go/v2/dist/index.js:5549:12)
    at Object.<anonymous> (/actions-runner/_work/_actions/actions/setup-go/v2/dist/index.js:204:22)
    at Generator.next (<anonymous>)
    at /actions-runner/_work/_actions/actions/setup-go/v2/dist/index.js:57:71
    at new Promise (<anonymous>)
(node:3076949) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3076949) [DEP00[18](https://github.rockstargames.com/tech-art/rsg_grpc_transcoding/runs/48704?check_suite_focus=true#step:5:18)] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
go version go1.18.1 linux/amd64
```

**Comment by ginwakeup** [comment]
> Hello @ginwakeup. Could you please provide a public repository to reproduce the issue ?

I could find the reason for this. It seems like self-hosted runners do not provide a HOME directory, therefore the action setup-go cannot work.

I've added the HOME env var to the action and everything works fine.
